services:
  openldr-kafka-zoo1:
    image: confluentinc/cp-zookeeper:7.7.1
    hostname: openldr-kafka-zoo1
    container_name: openldr-kafka-zoo1
    restart: unless-stopped
    # ports:
    #   # Zookeeper client port (2181) - Internal port for Kafka cluster coordination
    #   - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_SERVERS: openldr-kafka-zoo1:2888:3888
    networks:
      - openldr-network
    deploy:
      resources:
        limits:
          # cpus: ${CPU_LIMIT}
          memory: 2G
        reservations:
          memory: 1024M
    memswap_limit: 3G
    volumes:
      - zoo-data:/var/lib/zookeeper/data
      - zoo-log:/var/lib/zookeeper/log
  openldr-kafka1:
    image: confluentinc/cp-kafka:7.7.1
    hostname: openldr-kafka1
    container_name: openldr-kafka1
    restart: unless-stopped
    # ports:
    #   - "${KAFKA_EXTERNAL_PORT}:9092" # Map external port to Kafka's external listener
    #   - "${KAFKA_DOCKER_PORT}:29092" # Map docker port to Kafka's docker listener
    #   - "19092:19092" # Expose internal port (optional, for debugging)
    #   - "9999:9999" # Kafka metrics port (9999) - Internal port for Kafka metrics collection
    environment:
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://openldr-kafka1:19092,EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:${KAFKA_EXTERNAL_PORT},DOCKER://localhost:${KAFKA_DOCKER_PORT}
      # KAFKA_ADVERTISED_LISTENERS: INTERNAL://openldr-kafka1:19092,EXTERNAL://${DOCKER_HOST_IP}:${KAFKA_EXTERNAL_PORT},DOCKER://host.docker.internal:${KAFKA_DOCKER_PORT}
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:19092,EXTERNAL://0.0.0.0:9092,DOCKER://0.0.0.0:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,DOCKER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: "openldr-kafka-zoo1:2181"
      KAFKA_BROKER_ID: 1
      KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1 # good default for dev
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1 # good default for dev
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1 # good default for dev
      # Kafka JMX port (9001) - Internal port for Java Management Extensions monitoring
      KAFKA_JMX_PORT: 9001
      KAFKA_JMX_HOSTNAME: ${DOCKER_HOST_IP}
      KAFKA_AUTHORIZER_CLASS_NAME: kafka.security.authorizer.AclAuthorizer # good default
      KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND: "true" # good default for dev
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "/usr/bin/kafka-topics --bootstrap-server openldr-kafka1:19092 --list || exit 1",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s # Increased to give more startup time
    depends_on:
      - openldr-kafka-zoo1
    networks:
      - openldr-network
    volumes:
      - kafka-data:/var/lib/kafka/data
    deploy:
      resources:
        limits:
          # cpus: ${CPU_LIMIT}
          memory: 2G
        reservations:
          memory: 1024M
    memswap_limit: 3G
  openldr-kafka-connect:
    image: confluentinc/cp-kafka-connect:7.7.1
    hostname: openldr-kafka-connect
    container_name: openldr-kafka-connect
    restart: unless-stopped
    # ports:
    #   - "${KAFKA_CONNECT_PORT}:8083"
    deploy:
      resources:
        limits:
          # cpus: ${CPU_LIMIT}
          memory: 2G
        reservations:
          memory: 1024M
    memswap_limit: 3G
    environment:
      CONNECT_BOOTSTRAP_SERVERS: "openldr-kafka1:19092"
      CONNECT_REST_PORT: 8083
      CONNECT_GROUP_ID: compose-connect-group
      CONNECT_CONFIG_STORAGE_TOPIC: connect-configs # good default - internal topics to manage connect
      CONNECT_OFFSET_STORAGE_TOPIC: connect-offsets # good default - internal topics to manage connect
      CONNECT_STATUS_STORAGE_TOPIC: connect-status # good default - internal topics to manage connect
      CONNECT_KEY_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_KEY_CONVERTER_SCHEMAS_ENABLE: "false"
      CONNECT_VALUE_CONVERTER_SCHEMAS_ENABLE: "false"
      CONNECT_INTERNAL_KEY_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_INTERNAL_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_REST_ADVERTISED_HOST_NAME: "openldr-kafka-connect"
      CONNECT_LOG4J_ROOT_LOGLEVEL: "INFO" # good default
      CONNECT_LOG4J_LOGGERS: "org.apache.kafka.connect.runtime.rest=WARN,org.reflections=ERROR" # good default
      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: "1" # good default dev
      CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: "1" # good default dev
      CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: "1" # good default dev
      CONNECT_PLUGIN_PATH: "/etc/kafka-connect/jars" # Removed /usr/share/java, /usr/share/confluent-hub-components
    volumes:
      - ./kafka-connect:/etc/kafka-connect/jars/
    depends_on:
      openldr-kafka1:
        condition: service_healthy
      openldr-kafka-zoo1:
        condition: service_started
    command: |
      bash -c '
        echo "Starting Kafka Connect worker"
        /etc/confluent/docker/run &
        echo "Kafka Connect worker started"
        sleep infinity
      '
    networks:
      - openldr-network
    healthcheck:
      test: ["CMD-SHELL", "curl -s -f http://localhost:8083/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s # Increased start period

  openldr-kafka-conduktor-console:
    image: conduktor/conduktor-console:1.41.0
    hostname: openldr-kafka-conduktor-console
    container_name: openldr-kafka-conduktor-console
    restart: unless-stopped
    user: "0:0"
    # ports:
    #   - "${KAFKA_CONDUKTOR_PORT}:8080"
    deploy:
      resources:
        limits:
          # cpus: ${CPU_LIMIT}
          memory: 2G
        reservations:
          memory: 1024M
    memswap_limit: 3G
    volumes:
      - ./conduktor-data:/var/conduktor
    environment:
      CDK_ADMIN_EMAIL: "${KAFKA_CONDUKTOR_USERNAME}" # look to add env variable for this
      CDK_ADMIN_PASSWORD: "${KAFKA_CONDUKTOR_PASSWORD}" # look to add env variable for this
      CDK_DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOSTNAME}:5432/conduktor_console"
      CDK_CLUSTERS_0_ID: "default"
      CDK_CLUSTERS_0_NAME: "OpenLDR Kafka"
      CDK_CLUSTERS_0_COLOR: "#0013E7"
      CDK_CLUSTERS_0_BOOTSTRAPSERVERS: "PLAINTEXT://openldr-kafka1:19092"
      CDK_CLUSTERS_0_KAFKACONNECTS_0_URL: "http://openldr-kafka-connect:8083"
      CDK_CLUSTERS_0_KAFKACONNECTS_0_NAME: "full stack kafka connect"
      # These are the critical settings for subpath
      # CDK_PLATFORM_EXTERNAL_URL: "https://${HOST_IP}/kafka-console/"
      # SERVER_SERVLET_CONTEXT_PATH: "/kafka-console"
    networks:
      - openldr-network

volumes:
  conduktor-data: {}
  kafka-data: {}
  kafka-connect: {}
  zoo-data: {}
  zoo-log: {}

networks:
  openldr-network:
    driver: bridge
