services:
  openldr-plugins:
    image: openldr-plugins:latest
    build:
      context: ../../
      dockerfile: ./apps/openldr-plugins/Dockerfile
    container_name: openldr-plugins
    hostname: openldr-plugins
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: ${CPU_LIMIT}
          memory: ${MEMORY_LIMIT}
        reservations:
          memory: ${MEMORY_RESERVATIONS}
    memswap_limit: ${MEMSWAP_LIMIT}
    env_file:
      - .env
    ports:
      - "${PLUGIN_PORT}:3006"
    networks:
      - openldr-network

networks:
  openldr-network:
    external: true
