services:
  openldr-terminology-mapping:
    image: openldr-terminology-mapping:latest
    build:
      context: ../../
      dockerfile: ./apps/openldr-terminology-mapping/Dockerfile
    container_name: openldr-terminology-mapping
    hostname: openldr-terminology-mapping
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: ${CPU_LIMIT}
          memory: ${MEMORY_LIMIT}
        reservations:
          memory: ${MEMORY_RESERVATIONS}
    memswap_limit: ${MEMSWAP_LIMIT}
    env_file:
      - .env
    ports:
      - "${TERMINOLOGY_MAPPING_PORT}:3007"
    networks:
      - openldr-network

networks:
  openldr-network:
    external: true
